user:
  outputs:
    default:
      job_execution_timeout_seconds: 300
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: data-warehousing@dtc-de-course-491308.iam.gserviceaccount.com
        client_id: '114396692400323735482'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/data-warehousing%40dtc-de-course-491308.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDrsNiFS5Td42Ur

          MzY72WBFJg3GdrSbhAG4K4LP2aPJTv0+6f10Ms2wNRLJ0uKdNGY1HvdO44idfpKC

          G/hI9/WXO1ODjCLevZtyV+OTIFTHcvLe+/0aGaBIXoGejvW2xgOOuxQxgmLeQob2

          XTq1nz2t2eP+itBA9HUZpQmgLfo6aFlN7yQ5U8VFYTm8OdABzs+Nlyj2EVd9rjuX

          gaFOzbVLN06NHkVc6LB9lqdNatSOS/C/dmv1kT7SGYuQ3m1yH52UeYWMHIZhK8Lk

          IQhVSfyB3qRFThfTohbbW7ZDXDQ0bPFqJSV+F7Wm/pEpVfZsOOtX2yTWoB2VSfUt

          1q/ewyB1AgMBAAECggEAIt4KCh4rqxpwOxCGc3Atx80LY1LoVna+8l9YKND1DrD6

          0gs3uFr+XD+zGdxy3fgvLqiixC7xD6uhQlJKTDEynz7i6fvEpNhpXg8WgbYvae+I

          HT4rgWhNHVJYhqZ2P1B9R5OcNyl84DijUrW+xmOvx5ULyk+q42ZxdGvFSBxv1Pfr

          ldAGOJJoENZB2Ce/Lum1smmxXySZ/tTYYkQzmExkOMH3x8ufYoidsGMzUFExz6Nm

          j1ddQYNbtodoXQH+hhzZdg3VTcdgrUJgFZTnUyYuiMqc3nDEKrECm3dHkqi2EwM1

          xl79a2xdG/f9W8lNfqA4f/wvEDxWi/1y43UAmqrcOQKBgQD+KHJC6j8kVnKPClkq

          FauIHtZ3rfyCEC0uuxSTdwOghR4pDez79SBIEp4DzBojJmsHDkfGzhUjEsegL1pb

          cobS6vWZZw00+UcXryiu8qTIHqC+947m5IPf4e3/9AXRxuYLstpZ8+1aeFlIZ1Dr

          9YLf9pgk14/HSSC9Rtrj6rnAnwKBgQDtZiLgD5r1KnmAQsLCFlyB/pXIOztfKxnh

          4WRlpqRqJzDy9wgeEBE1ODLKCH4a8uR2oxoRsEdj7CkOl+9R6XgGsxwm+/BcJPlj

          H7cAJ4wue4nukfxPa0sjcKgOYRLgFcuHMvfR+LNCDdKBo5WUixXT49KPSoIjInWu

          GZPQd+WiawKBgFWezo9YVpkpPkKN2+ffkP+0U8/RnyU5yd7aS146U9B5x+VQuatP

          suZUz0K8OXnp8VhZKTkCKAC+zN1b1nbEKENZwA9DtiFIcPi7m1sEhxqbps9umoeS

          KBL+C62USXmYJdt/DywKjsVRkdJga9RxyvskGbEfpWIfcpYRDqCFbLpFAoGBAJ7o

          2H19VK+5v90QU0gSKdhGb0K6C3MX6dpewpKcqr/3/fcVTxS4kpw6Qx0j9C3b2vxj

          D0c55X/IjG8dWvBMxLBPYo/h4zH6+gjVKO1si5Rt05WjmO4clw5hEc2WQ0lGrZeR

          kXu2619S2082DiGBvJm6ja6nJFeacIWaz2wjZc6DAoGAXYI6+gaJOFUcCZ1e8fOB

          PG31jEQWyU+5jcL9wu+TWEjLpwbcCgD8YX4zpYTWLRhGgBnO7cPetuvabLI8bcjc

          kYr/KGETVblw2TKXl9RQFnutqH4vzICYvR6YcXpBuFgHE+9z3OEojMvbvK+RK1Of

          brJVEj0klEMxtO5R1752gfM=

          -----END PRIVATE KEY-----

          '
        private_key_id: b4880ee4485985534613519ff953cfd089a92a5b
        project_id: dtc-de-course-491308
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: US
      maximum_bytes_billed: 1000000000
      method: service-account-json
      project: dtc-de-course-491308
      schema: dbt_luis
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 6
      type: bigquery
  target: default
