#!/bin/bash

# Start DB and pgAdmin
docker compose up -d

# Run ingestion for trips
docker compose run --rm ingestor \
  --target-table=green_tripdata_2025_11 \
  --url="https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"

# Run ingestion for zones
docker compose run --rm ingestor \
  --target-table=taxi_zone_lookup \
  --url="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

