services:
  taxi:
    build:
      context: .
      dockerfile: Dockerfile
    image: taxi_upload:v002
    volumes:
      - /home/andres/.gcp:/app/.gcp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.gcp/warehousing_hw3_key.json
